trigger: none 

pool: Default

stages:
- stage: setup_nodejs
  displayName: install_runtime_env_node
  
  jobs:
  - job: installnodejs
    steps:

    -  checkout: self

    - task: NodeAndNpmTool@1
      inputs:
        versionSpec: '16.x'
        checkLatest: true

