trigger: none 

pool: Default

stages:
- stage: setup_nodejs
  displayName: install_runtime_env_node
  
  jobs:
  - job: installnodejs
    steps:

    -  checkout: self
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '16'

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          npm run build
            dir build

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/build'
        artifact: 'todo-arti'
        publishLocation: 'pipeline'

# stages:
# - stage: setup_nodejs
#   displayName: install_runtime_env_node
  
#   jobs:
#   - job: installnodejs
#     steps:



