trigger: none 

pool: Default

stages:
- stage: setup_nodejs
  displayName: install_runtime_env_node
  
  jobs:
  - job: installnodejs
    steps:

    -  checkout: self
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '16'

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          npm run build
            dir build

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/build'
        artifact: 'todo-arti'
        publishLocation: 'pipeline'


- stage: Build_Artifact
  displayName: Build and Archive Artifacts
  dependsOn: setup_nodejs
  jobs:
  - job: ArchiveAnd_and_Publish
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'todo-arti'
        targetPath: '$(Pipeline.Workspace)/todo-arti'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/todo-arti'
        includeRootFolder: true
        archiveType: '7z'
        archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/build.zip'
        artifact: 'todo-arti'
        publishLocation: 'pipeline'